<?php
/**
 * @file
 * Code for the Stanford Sweeteners feature.
 */

include_once 'stanford_sweeteners.features.inc';

/**
 * Implements hook_help().
 */
function stanford_sweeteners_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/help#stanford_sweeteners':
      return '<p>' . t('Contact your site administrator') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function stanford_sweeteners_menu() {
  $items = array();
  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function stanford_sweeteners_libraries_info() {
  $libraries = array();

  $libraries['slick'] = array(
    'name' => 'Slick Carousel',
    'vendor url' => 'http://kenwheeler.github.io/slick/',
    'download url' => 'https://github.com/kenwheeler/slick/archive/1.4.0.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/(\d+\.?\d+\.?\d+\.?)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'slick/slick.min.js',
      ),
      'css' => array(
        'slick/slick.css',
        'slick/slick-theme.css',
      )
    ),
  );

  return $libraries;
}

/**
 * Implements pre_render so we can attach css or libraries if needed.
 * @param  [type] &$view [description]
 * @return [type]        [description]
 */
function stanford_sweeteners_views_pre_render(&$view) {
  if (strpos($view->name, "sweetener") !== FALSE) {
    $class = $view->display_handler->get_option('css_class');
    if (strpos($class, "slick-carousel") !== FALSE) {
      // Generate a random ID to use.
      $id = "srand-" . md5(rand(0, 100000) + time());
      $view->display_handler->set_option('css_class', $class . " " . $id);
      libraries_load('slick');
      $settings = stanford_sweeteners_load_slick_settings($id, "responsive");
    }
  }
}

/**
 * [stanford_sweeteners_load_slick_settings description]
 * @param  [type] $type [description]
 * @param  [type] $opts [description]
 * @return [type]       [description]
 */
function stanford_sweeteners_load_slick_settings($id, $type = "default", $opts = array()) {
  $settings = stanford_sweeteners_get_slick_settings($type, $opts);
  drupal_add_js(array("stanford_sweeteners" => array($id => $settings)), 'setting');
  drupal_add_js(drupal_get_path("module", "stanford_sweeteners") . "/js/stanford_sweeteners.slick.js");
  drupal_add_css(drupal_get_path("module", "stanford_sweeteners") . "/css/stanford_sweeteners.css");
}

/**
 * [stanford_sweeteners_get_slick_settings description]
 * @param  string $type [description]
 * @return [type]       [description]
 */
function stanford_sweeteners_get_slick_settings($type = "default", $opts = array()) {
  $settings = array();

  // Default
  // -----------------------------------------------------------------

  $settings['default'] = array();

  // Num items
  // -----------------------------------------------------------------

  $settings['number_of_items'] = array(
    "infinite" => TRUE,
    "slidesToShow" => isset($opts['num']) ? $opts['num'] : 1,
    "slidesToScroll" => isset($opts['num']) ? $opts['num'] : 1,
  );

  // Redundant. Cuz its funny.
  // -----------------------------------------------------------------

  $settings['redundant'] = $opts;

  // Responsive
  // -----------------------------------------------------------------

  $settings["responsive"] = array(
    "dots" => FALSE,
    "infinite" => TRUE,
    "speed" => 300,
    "slidesToShow" => 3,
    "slidesToScroll" => 3,
    "responsive" => array(
      array(
        "breakpoint" => 1024,
        "settings" => array(
          "slidesToShow" => 2,
          "slidesToScroll" => 2,
          "infinite" => TRUE,
          "dots" => TRUE,
        ),
      ),
      array(
        "breakpoint" => 600,
        "settings" => array(
          "slidesToShow" => 1,
          "slidesToScroll" => 1
        ),
      ),
    ),
  );

  return isset($settings[$type]) ? $settings[$type] : FALSE;
}


